name: ci

on:
  push:
    branches:
      - "feat/create_pipeline"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/note:latest
          
   deploy:
    runs-on: ubuntu-latest
  
    steps:
      - name: Install sshpass
        run: sudo apt-get update && sudo apt-get install -y sshpass
  
      - name: Deploy to Raspberry Pi
        run: |
          sshpass -p ${{ secrets.SSH_PASSWORD }} ssh ${{ secrets.PI_USERNAME }}@${{ secrets.PI_HOST }} 'docker pull note'
          sshpass -p ${{ secrets.SSH_PASSWORD }} ssh ${{ secrets.PI_USERNAME }}@${{ secrets.PI_HOST }} 'docker run -d --name note note'