name: Deploy to Raspberry Pi

on:
  push:
    branches:
      - feat/create_pipeline

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-qemu-action@v1

      - name: Build Docker image
        run: docker build -t note .

      - name: Log in to Docker Hub (or your container registry)
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin ${{ secrets.DOCKER_PASSWORD }} 

      - name: Push Docker image
        run: docker push note
        
 deploy:
  runs-on: ubuntu-latest

  steps:
    - name: Install sshpass
      run: sudo apt-get update && sudo apt-get install -y sshpass

    - name: Deploy to Raspberry Pi
      run: |
        sshpass -p ${{ secrets.SSH_PASSWORD }} ssh ${{ secrets.PI_USERNAME }}@${{ secrets.PI_HOST }} 'docker pull note'
        sshpass -p ${{ secrets.SSH_PASSWORD }} ssh ${{ secrets.PI_USERNAME }}@${{ secrets.PI_HOST }} 'docker run -d --name note note'
